
package com.wqzhang.iwebserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoService", targetNamespace = "http://server.iwebserver.wqzhang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://server.iwebserver.wqzhang.com/", className = "com.wqzhang.iwebserver.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://server.iwebserver.wqzhang.com/", className = "com.wqzhang.iwebserver.GetNameResponse")
    public String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
